FROM python:3.12-slim

WORKDIR /app

COPY requirements.txt .

RUN echo "sqlalchemy" >> requirements.txt \
    && pip install --no-cache-dir -r requirements.txt \
    && apt-get update && apt-get install -y default-mysql-client \
    && rm -rf /var/lib/apt/lists/*

COPY . .

CMD ["python", "safe_dump_aggregate.py"]
